# fly.toml app configuration file generated for pytho on 2023-05-05T14:16:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pytho"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[build.args]
  MODE="production"
